version: "3.9"
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - DB_TYPE=$DB_TYPE
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
